### ISSUE TITLE
☢️ Codigo 'fallando' (?)

### ISSUE THREAD

**Issue by HoyosQ** [enflujo/colev-twitter-api#13]
![image](https://user-images.githubusercontent.com/89080958/218584227-6d6f3da4-0659-4ee3-a52c-3ad56c63ad7c.png)

@1cgonza Esta marcando como si el codigo estuviera fallando, no se si es algo de prioridad alta o nah.

**Comment by 1cgonza** [comment]
@HoyosQ este repositorio se va a sepultar cuando termine lo que estoy haciendo justo ahora porque lo que estaba acá lo pasé al repositorio `colev-api`. Entonces no nos preocupemos, pero gracias por el aviso!
